version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    command: ["--bind_ip_all"]
    env_file:
      - ./.mongo.env  
    volumes:
     - ./database_startup:/docker-entrypoint-initdb.d:ro
    ports:
      - '27017-27019:27017-27019'
