version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    command: ["--bind_ip_all"]
    env_file:
      - ./.mongo.env  
    volumes:
     - ./database_startup:/docker-entrypoint-initdb.d:ro
    ports:
      - '27017-27019:27017-27019'
  file-storage:
    image: minio/minio:RELEASE.2020-07-02T00-15-09Z
    volumes: 
      - storage_1:/data
    ports: 
      - "9001:9000"
    env_file: 
      - ./.minio.env
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  storage_1: 

